#!/bin/sh

# Aliases defined by platform
arch=`uname -s`

case $arch in
  SunOS)
    # Directories Listings
    [ -f /opt/csw/bin/gls ] && alias ls='/opt/csw/bin/gls --color=auto'
    alias ll='ls -a -h -F -l'
    alias l1='ls -A -1'
    alias lw='l1 | wc -l'
    alias l='ll'

    # Directories Navigation & Handling
    alias ..='cd ..'
    alias ..2='cd ../..'
    alias ..3='cd ../../..'
    alias ..4='cd ../../../..'
    alias ..5='cd ../../../../..'

    # Verbose File Operations
    [ -f /opt/csw/bin/gcp ] && alias cp='/opt/csw/bin/gcp -i -v'
    [ -f /opt/csw/bin/gmv ] && alias mv='/opt/csw/bin/gmv -i -v'
    [ -f /opt/csw/bin/grm ] && alias rm='/opt/csw/bin/grm -i -v'

    # File System Listings
    [ -f /opt/csw/bin/gdf ] && alias df='/opt/csw/bin/gdf -P'
    alias df='df -h'

    # Vim
    [ -f /opt/csw/bin/vim ] && alias vim='/opt/csw/bin/vim'
    alias vi='vim'

    # Sudo
    alias s='sudo'
    alias ssu='sudo su -'
    ;;

  Linux)
    # Directories Listings
    alias ls='ls --color=auto'
    alias ll='ls --all --human-readable --classify -l'
    alias l1='ls --almost-all -1'
    alias lw='l1 | wc -l'
    alias l='ll'

    # Directories Navigation & Handling
    alias ..='cd ..'
    alias ..2='cd ../..'
    alias ..3='cd ../../..'
    alias ..4='cd ../../../..'
    alias ..5='cd ../../../../..'

    # Verbose/Interactive File Operations
    alias cp='cp -i -v'
    alias mv='mv -i -v'
    alias rm='rm -i -v'

    # File System Listings
    alias df='df -h -P'

    # Vim
    [ -f /usr/local/bin/vim ] && alias vim='/usr/local/bin/vim'
    [ -f /usr/local/bin/vimdiff ] && alias vimdiff='/usr/local/bin/vimdiff'
    [ -f /usr/local/bin/vimtutor ] && alias vimtutor='/usr/local/bin/vimtutor'
    alias vi='vim'

    # Sudo
    alias s='sudo'
    alias ssu='sudo su -'
    ;;

  AIX)
    # Directories Listings
    alias ls='ls'
    alias ll='ls -a -F -l'
    alias l1='ls -A -1'
    alias lw='l1 | wc -l'
    alias l='ll'

    # Directories Navigation & Handling
    alias ..='cd ..'
    alias ..2='cd ../..'
    alias ..3='cd ../../..'
    alias ..4='cd ../../../..'
    alias ..5='cd ../../../../..'

    # Verbose File Operations
    alias cp='cp -i'
    alias mv='mv -i'
    alias rm='rm -i'

    # File System Listings
    alias df='df -g -P'

    # Vim
    alias vi='vim'

    # Sudo
    alias s='sudo'
    alias ssu='sudo su -'
    ;;

  *)
    ;;
esac


# Infra Servers
if (hostname | egrep 'ldxx90infra1|ldxx90infra2' > /dev/null); then
  # SSH
  alias ssh='/usr/bin/ssh -q'
  alias scp='/usr/bin/scp -q'
  alias sshi='sudo /usr/bin/ssh -q'
  alias scpi='sudo /usr/bin/scp -q'

  # Tmux
  alias tmux='[ -z "$TMUX" ] && TERM=xterm-256color tmux'

  # Irssi
  alias irssi='TERM=screen-256color irssi'
fi
