#!/bin/bash
#
# bashrc (NDF::BASH)
#

# Load the '/etc/bashrc' file first
[ -s /etc/bashrc ] && source /etc/bashrc

# Load component '~/.aliases'
[ -s ~/.aliases ] && source ~/.aliases

# Setup TERM
export TERM=xterm

# Setup Editor
export EDITOR=vi
export GIT_EDITOR=vi

# Ve Improved
set -o vi
